### ISSUE TITLE
league/html-to-markdown forced to version 4

### ISSUE THREAD

**Issue by bashgeek** [spatie/mailcoach-ui#12]
Is there any particular reason why `league/html-to-markdown` is forced to version 4 instead of version 5 here? `spatie/laravel-mailcoach` is supporting v5 already and the changes don't look too breaking, so maybe there is a particular reason for it that I'm unaware of - otherwise I'm happy to send in a small PR.

**Comment by freekmurze** [comment]
This is an oversight from our part. Feel free to PR support for v5.
