### ISSUE TITLE
CREATE USER CONTROLLE FLASH MESSAGE ISSUE

### ISSUE THREAD

**Issue by codec1120** [spatie/mailcoach-ui#4]
Hello! 

Can we use the laravel helper __( ) on flashing success message? so that It can read the parameter "email" ?

![Screenshot_3](https://user-images.githubusercontent.com/51552197/111954182-a8ad2300-8b22-11eb-8e12-03760a43e8db.png)

**Comment by riasvdv** [comment]
Fixed!

**Comment by codec1120** [comment]
Thanks :)
